### ISSUE TITLE
[BUG] Bandit tool report - Part 4

### ISSUE THREAD

**Issue by slashdd** [jduncan-rva/soscleaner#119]
```
>> Issue: [B605:start_process_with_a_shell] Starting a process with a shell, possible injection detected, security issue.
   Severity: High   Confidence: High
   Location: soscleaner/soscleaner.py:224
223	                command = "file %s" % filename
224	                filetype = os.popen(command).read().strip('\n').split(':')[1].strip().lower()
225	                if 'text' in filetype:

--------------------------------------------------
>> Issue: [B605:start_process_with_a_shell] Starting a process with a shell, possible injection detected, security issue.
   Severity: High   Confidence: High
   Location: soscleaner/soscleaner.py:305
304	                command = "file %s" % filename
305	                compression_type = os.popen(command).read().strip('\n').split(':')[1].strip().lower()
306	                return compression_type

```

**Comment by slashdd** [comment]
Should be a matter of using subprocess.Popen(), os.popen() is consider a older function:
https://docs.python.org/2.7/library/subprocess.html

**Comment by jduncan-rva** [comment]
These were fixed by other issues, right?

**Comment by slashdd** [comment]
AFAIK, I don't think this was solved yet.

**Comment by slashdd** [comment]
I just checked and it's still present in bandit report:
>> Issue: [B605:start_process_with_a_shell] Starting a process with a shell, possible injection detected, security issue.
   Severity: High   Confidence: High
   Location: soscleaner/soscleaner.py:254
253	                command = "file %s" % filename
254	                filetype = os.popen(command).read().strip(
255	                    '\n').split(':')[1].strip().lower()

--------------------------------------------------
>> Issue: [B605:start_process_with_a_shell] Starting a process with a shell, possible injection detected, security issue.
   Severity: High   Confidence: High
   Location: soscleaner/soscleaner.py:348
347	                command = "file %s" % filename
348	                compression_type = os.popen(command).read().strip(
349	                    '\n').split(':')[1].strip().lower()

--------------------------------------------------

So definitely need to be address as a security concern.

**Comment by jduncan-rva** [comment]
do you want to resolve this in 0.4.5, or 0.5.0?
